---
    - name: Install Apache using dnf
      dnf:
        name: httpd
        state: present

    - name: start and enable autostart of apache server
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Status of httpd
      ansible.builtin.service:
        name: httpd
        state: reloaded  
        
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Update all packages to the latest version
      dnf:
        name: "*"
        state: latest

    - name: Install required dependencies
      dnf:
        name: 
          - dnf-plugins-core
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      copy:
        dest: /etc/yum.repos.d/docker.repo
        content: |
          [docker-ce-stable]
          name=Docker CE Stable - $basearch
          baseurl=https://download.docker.com/linux/centos/7/$basearch/stable
          enabled=1
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      dnf:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - debug:
        msg: "Docker version is {{ docker_version.stdout }}"