---
- name: Ubuntu Playbook
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Include ubuntu webserver Install
      import_tasks: ubuntu.yml
    - name: Include install docker
      import_tasks: dockerU.yml
    
   