---
- name: Setup web server, SQL, and Node.js on Ubuntu
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  gather_facts: yes

  tasks:
    - name: Install packages on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - mysql-server
        - nodejs
        - npm

    - name: Start and enable services on Ubuntu
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql
        
- name: Setup web server, SQL, and Node.js on Amazon Linux
  hosts: amazon_linux
  remote_user: ec2-user
  become: yes
  gather_facts: yes

  tasks:
    - name: Install packages on Amazon Linux
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - nodejs
        - npm
        - postgresql15
        - postgresql15-server

    - name: Initialize PostgreSQL database
      command: "/usr/bin/initdb -D /var/lib/pgsql/test1"
      become: yes
      become_user: postgres
      when: ansible_distribution == 'Amazon'

    - name: Start and enable services on Amazon Linux
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd

